//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Button {
            get {
                return ResourceManager.GetString("About_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionCategory_Button {
            get {
                return ResourceManager.GetString("ActionCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Button {
            get {
                return ResourceManager.GetString("Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom aliases.
        /// </summary>
        public static string Alias_Binding {
            get {
                return ResourceManager.GetString("Alias_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Attack {
            get {
                return ResourceManager.GetString("Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary fire.
        /// </summary>
        public static string Attack2 {
            get {
                return ResourceManager.GetString("Attack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto buy.
        /// </summary>
        public static string Autobuy {
            get {
                return ResourceManager.GetString("Autobuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bot [CT].
        /// </summary>
        public static string Bot_add_ct {
            get {
                return ResourceManager.GetString("Bot_add_ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bot [T].
        /// </summary>
        public static string Bot_add_t {
            get {
                return ResourceManager.GetString("Bot_add_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place bot.
        /// </summary>
        public static string Bot_place {
            get {
                return ResourceManager.GetString("Bot_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy menu.
        /// </summary>
        public static string Buymenu {
            get {
                return ResourceManager.GetString("Buymenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy items.
        /// </summary>
        public static string BuyScenario {
            get {
                return ResourceManager.GetString("BuyScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy scenario.
        /// </summary>
        public static string BuyScenarioCategory_Button {
            get {
                return ResourceManager.GetString("BuyScenarioCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call vote.
        /// </summary>
        public static string Callvote {
            get {
                return ResourceManager.GetString("Callvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be empty.
        /// </summary>
        public static string CanNotBeEmpty_Error {
            get {
                return ResourceManager.GetString("CanNotBeEmpty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus scripts.
        /// </summary>
        public static string CategoryBonusScripts {
            get {
                return ResourceManager.GetString("CategoryBonusScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots.
        /// </summary>
        public static string CategoryBots {
            get {
                return ResourceManager.GetString("CategoryBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy commands.
        /// </summary>
        public static string CategoryBuy {
            get {
                return ResourceManager.GetString("CategoryBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client commands.
        /// </summary>
        public static string CategoryClientCommands {
            get {
                return ResourceManager.GetString("CategoryClientCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common actions.
        /// </summary>
        public static string CategoryCommonActions {
            get {
                return ResourceManager.GetString("CategoryCommonActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string CategoryCommunication {
            get {
                return ResourceManager.GetString("CategoryCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair.
        /// </summary>
        public static string CategoryCrosshair {
            get {
                return ResourceManager.GetString("CategoryCrosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string CategoryDemo {
            get {
                return ResourceManager.GetString("CategoryDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string CategoryEquipment {
            get {
                return ResourceManager.GetString("CategoryEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse settings.
        /// </summary>
        public static string CategoryMouseSettings {
            get {
                return ResourceManager.GetString("CategoryMouseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string CategoryMovement {
            get {
                return ResourceManager.GetString("CategoryMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net_graph settings.
        /// </summary>
        public static string CategoryNetGraphSettings {
            get {
                return ResourceManager.GetString("CategoryNetGraphSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CategoryOther {
            get {
                return ResourceManager.GetString("CategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string CategoryServer {
            get {
                return ResourceManager.GetString("CategoryServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice and sound.
        /// </summary>
        public static string CategoryVoiceAndSound {
            get {
                return ResourceManager.GetString("CategoryVoiceAndSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmup.
        /// </summary>
        public static string CategoryWarmup {
            get {
                return ResourceManager.GetString("CategoryWarmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear hint history.
        /// </summary>
        public static string Cl_clearhinthistory {
            get {
                return ResourceManager.GetString("Cl_clearhinthistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show team equipment.
        /// </summary>
        public static string Cl_show_team_equipment {
            get {
                return ResourceManager.GetString("Cl_show_team_equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear console.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name:.
        /// </summary>
        public static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands executed by default.
        /// </summary>
        public static string CommandsByDefault_Hint {
            get {
                return ResourceManager.GetString("CommandsByDefault_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands bound to custom alias.
        /// </summary>
        public static string CommandsInAlias_Hint {
            get {
                return ResourceManager.GetString("CommandsInAlias_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config name.
        /// </summary>
        public static string ConfigName_Hint {
            get {
                return ResourceManager.GetString("ConfigName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle crosshairs.
        /// </summary>
        public static string CrosshairLoop {
            get {
                return ResourceManager.GetString("CrosshairLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO path.
        /// </summary>
        public static string CsgoPath_Hint {
            get {
                return ResourceManager.GetString("CsgoPath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default commands.
        /// </summary>
        public static string Default_Binding {
            get {
                return ResourceManager.GetString("Default_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume demo.
        /// </summary>
        public static string Demo_resume {
            get {
                return ResourceManager.GetString("Demo_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle demo pause.
        /// </summary>
        public static string Demo_togglepause {
            get {
                return ResourceManager.GetString("Demo_togglepause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display damage OFF.
        /// </summary>
        public static string DisplayDamage_Off {
            get {
                return ResourceManager.GetString("DisplayDamage_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display damage ON.
        /// </summary>
        public static string DisplayDamage_On {
            get {
                return ResourceManager.GetString("DisplayDamage_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duck.
        /// </summary>
        public static string Duck {
            get {
                return ResourceManager.GetString("Duck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute command.
        /// </summary>
        public static string ExecCustomCmds {
            get {
                return ResourceManager.GetString("ExecCustomCmds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra alias.
        /// </summary>
        public static string ExtraAlias {
            get {
                return ResourceManager.GetString("ExtraAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra alias set.
        /// </summary>
        public static string ExtraAliasSet {
            get {
                return ResourceManager.GetString("ExtraAliasSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string ExtraCategory_Button {
            get {
                return ResourceManager.GetString("ExtraCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast bomb drop.
        /// </summary>
        public static string FastBombDrop {
            get {
                return ResourceManager.GetString("FastBombDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From_Label {
            get {
                return ResourceManager.GetString("From_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string GameSettingsCategory_Button {
            get {
                return ResourceManager.GetString("GameSettingsCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string Gear1 {
            get {
                return ResourceManager.GetString("Gear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West + helmet.
        /// </summary>
        public static string Gear2 {
            get {
                return ResourceManager.GetString("Gear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus.
        /// </summary>
        public static string Gear3 {
            get {
                return ResourceManager.GetString("Gear3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defuse kits.
        /// </summary>
        public static string Gear4 {
            get {
                return ResourceManager.GetString("Gear4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate config [.cfg].
        /// </summary>
        public static string GenerateConfig_Button {
            get {
                return ResourceManager.GetString("GenerateConfig_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate crosshairs.
        /// </summary>
        public static string GenerateCrosshairs_Button {
            get {
                return ResourceManager.GetString("GenerateCrosshairs_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God mode.
        /// </summary>
        public static string God {
            get {
                return ResourceManager.GetString("God", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molotov.
        /// </summary>
        public static string Grenade1 {
            get {
                return ResourceManager.GetString("Grenade1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        public static string Grenade2 {
            get {
                return ResourceManager.GetString("Grenade2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashbang.
        /// </summary>
        public static string Grenade3 {
            get {
                return ResourceManager.GetString("Grenade3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE.
        /// </summary>
        public static string Grenade4 {
            get {
                return ResourceManager.GetString("Grenade4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        public static string Grenade5 {
            get {
                return ResourceManager.GetString("Grenade5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades.
        /// </summary>
        public static string Grenades {
            get {
                return ResourceManager.GetString("Grenades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 1.
        /// </summary>
        public static string Health_Style0 {
            get {
                return ResourceManager.GetString("Health_Style0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 2.
        /// </summary>
        public static string Health_Style1 {
            get {
                return ResourceManager.GetString("Health_Style1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova.
        /// </summary>
        public static string Heavy1 {
            get {
                return ResourceManager.GetString("Heavy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XM1014.
        /// </summary>
        public static string Heavy2 {
            get {
                return ResourceManager.GetString("Heavy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sawed-Off/Mag7.
        /// </summary>
        public static string Heavy3 {
            get {
                return ResourceManager.GetString("Heavy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M249.
        /// </summary>
        public static string Heavy4 {
            get {
                return ResourceManager.GetString("Heavy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negev.
        /// </summary>
        public static string Heavy5 {
            get {
                return ResourceManager.GetString("Heavy5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Impulse_101 {
            get {
                return ResourceManager.GetString("Impulse 101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next weapon.
        /// </summary>
        public static string Invnext {
            get {
                return ResourceManager.GetString("Invnext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous weapon.
        /// </summary>
        public static string Invprev {
            get {
                return ResourceManager.GetString("Invprev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumpthrow script.
        /// </summary>
        public static string Jumpthrow {
            get {
                return ResourceManager.GetString("Jumpthrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard_Binding {
            get {
                return ResourceManager.GetString("Keyboard_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} pressure.
        /// </summary>
        public static string KeyDown1_Format {
            get {
                return ResourceManager.GetString("KeyDown1_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} pressure when {1} is pressed.
        /// </summary>
        public static string KeyDown2_Format {
            get {
                return ResourceManager.GetString("KeyDown2_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key pressure.
        /// </summary>
        public static string KeyPressure_Label {
            get {
                return ResourceManager.GetString("KeyPressure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key release.
        /// </summary>
        public static string KeyRelease_Label {
            get {
                return ResourceManager.GetString("KeyRelease_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} release.
        /// </summary>
        public static string KeyUp1_Format {
            get {
                return ResourceManager.GetString("KeyUp1_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} release when {1} is pressed.
        /// </summary>
        public static string KeyUp2_Format {
            get {
                return ResourceManager.GetString("KeyUp2_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last weapon.
        /// </summary>
        public static string Lastinv {
            get {
                return ResourceManager.GetString("Lastinv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightBlue.
        /// </summary>
        public static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect weapon.
        /// </summary>
        public static string Lookatweapon {
            get {
                return ResourceManager.GetString("Lookatweapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom acceleration.
        /// </summary>
        public static string m_customaccel {
            get {
                return ResourceManager.GetString("m_customaccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom acceleration exponent.
        /// </summary>
        public static string m_customaccel_exponent {
            get {
                return ResourceManager.GetString("m_customaccel_exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw input.
        /// </summary>
        public static string m_rawinput {
            get {
                return ResourceManager.GetString("m_rawinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Maker [eng].
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global chat.
        /// </summary>
        public static string Messagemode {
            get {
                return ResourceManager.GetString("Messagemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team chat.
        /// </summary>
        public static string Messagemode2 {
            get {
                return ResourceManager.GetString("Messagemode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        public static string Moveleft {
            get {
                return ResourceManager.GetString("Moveleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        public static string Moveright {
            get {
                return ResourceManager.GetString("Moveright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap teams.
        /// </summary>
        public static string Mp_swapteams {
            get {
                return ResourceManager.GetString("Mp_swapteams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End warmup.
        /// </summary>
        public static string Mp_warmup_end {
            get {
                return ResourceManager.GetString("Mp_warmup_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start warmup.
        /// </summary>
        public static string Mp_warmup_start {
            get {
                return ResourceManager.GetString("Mp_warmup_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noclip.
        /// </summary>
        public static string Noclip {
            get {
                return ResourceManager.GetString("Noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not CS:GO path.
        /// </summary>
        public static string NotCsgoPath_Error {
            get {
                return ResourceManager.GetString("NotCsgoPath_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glock/USP.
        /// </summary>
        public static string Pistol1 {
            get {
                return ResourceManager.GetString("Pistol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual berettas.
        /// </summary>
        public static string Pistol2 {
            get {
                return ResourceManager.GetString("Pistol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P250.
        /// </summary>
        public static string Pistol3 {
            get {
                return ResourceManager.GetString("Pistol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZ75/Fiveseven/Tec9.
        /// </summary>
        public static string Pistol4 {
            get {
                return ResourceManager.GetString("Pistol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deagle.
        /// </summary>
        public static string Pistol5 {
            get {
                return ResourceManager.GetString("Pistol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistols.
        /// </summary>
        public static string Pistols {
            get {
                return ResourceManager.GetString("Pistols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift for key sequence creating.
        /// </summary>
        public static string PressShift_Hint {
            get {
                return ResourceManager.GetString("PressShift_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit game.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear decals.
        /// </summary>
        public static string R_cleardecals {
            get {
                return ResourceManager.GetString("R_cleardecals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command radio.
        /// </summary>
        public static string Radio1 {
            get {
                return ResourceManager.GetString("Radio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standart radio.
        /// </summary>
        public static string Radio2 {
            get {
                return ResourceManager.GetString("Radio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report radio.
        /// </summary>
        public static string Radio3 {
            get {
                return ResourceManager.GetString("Radio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuy.
        /// </summary>
        public static string Rebuy {
            get {
                return ResourceManager.GetString("Rebuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove_Button {
            get {
                return ResourceManager.GetString("Remove_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galil/Famas.
        /// </summary>
        public static string Rifle1 {
            get {
                return ResourceManager.GetString("Rifle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AK47/M4.
        /// </summary>
        public static string Rifle2 {
            get {
                return ResourceManager.GetString("Rifle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSG08.
        /// </summary>
        public static string Rifle3 {
            get {
                return ResourceManager.GetString("Rifle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG553/AUG.
        /// </summary>
        public static string Rifle4 {
            get {
                return ResourceManager.GetString("Rifle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWP.
        /// </summary>
        public static string Rifle5 {
            get {
                return ResourceManager.GetString("Rifle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G3SG1/SCAR.
        /// </summary>
        public static string Rifle6 {
            get {
                return ResourceManager.GetString("Rifle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifles.
        /// </summary>
        public static string Rifles {
            get {
                return ResourceManager.GetString("Rifles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save config [.cmc].
        /// </summary>
        public static string SaveConfig_Button {
            get {
                return ResourceManager.GetString("SaveConfig_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screnshot.
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Hint {
            get {
                return ResourceManager.GetString("Search_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select config.
        /// </summary>
        public static string SelectConfig_Button {
            get {
                return ResourceManager.GetString("SelectConfig_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity.
        /// </summary>
        public static string sensitivity {
            get {
                return ResourceManager.GetString("sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle inventory display.
        /// </summary>
        public static string Show_loadout_toggle {
            get {
                return ResourceManager.GetString("Show_loadout_toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show avatars.
        /// </summary>
        public static string ShowAvatars {
            get {
                return ResourceManager.GetString("ShowAvatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show alive count.
        /// </summary>
        public static string ShowCount {
            get {
                return ResourceManager.GetString("ShowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string showscores {
            get {
                return ResourceManager.GetString("showscores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary weapon.
        /// </summary>
        public static string Slot1 {
            get {
                return ResourceManager.GetString("Slot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molotov.
        /// </summary>
        public static string Slot10 {
            get {
                return ResourceManager.GetString("Slot10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus.
        /// </summary>
        public static string Slot11 {
            get {
                return ResourceManager.GetString("Slot11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary weapon.
        /// </summary>
        public static string Slot2 {
            get {
                return ResourceManager.GetString("Slot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knife.
        /// </summary>
        public static string Slot3 {
            get {
                return ResourceManager.GetString("Slot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades.
        /// </summary>
        public static string Slot4 {
            get {
                return ResourceManager.GetString("Slot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        public static string Slot5 {
            get {
                return ResourceManager.GetString("Slot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE grenade.
        /// </summary>
        public static string Slot6 {
            get {
                return ResourceManager.GetString("Slot6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashbang.
        /// </summary>
        public static string Slot7 {
            get {
                return ResourceManager.GetString("Slot7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke grenade.
        /// </summary>
        public static string Slot8 {
            get {
                return ResourceManager.GetString("Slot8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        public static string Slot9 {
            get {
                return ResourceManager.GetString("Slot9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac10/MP9.
        /// </summary>
        public static string Smg1 {
            get {
                return ResourceManager.GetString("Smg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP7.
        /// </summary>
        public static string Smg2 {
            get {
                return ResourceManager.GetString("Smg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMP45.
        /// </summary>
        public static string Smg3 {
            get {
                return ResourceManager.GetString("Smg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P90.
        /// </summary>
        public static string Smg4 {
            get {
                return ResourceManager.GetString("Smg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP-Bizon.
        /// </summary>
        public static string Smg5 {
            get {
                return ResourceManager.GetString("Smg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string SMGs {
            get {
                return ResourceManager.GetString("SMGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graffiti menu.
        /// </summary>
        public static string Spray_menu {
            get {
                return ResourceManager.GetString("Spray_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step_Label {
            get {
                return ResourceManager.GetString("Step_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose team.
        /// </summary>
        public static string Teammenu {
            get {
                return ResourceManager.GetString("Teammenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To_Label {
            get {
                return ResourceManager.GetString("To_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Toggleconsole {
            get {
                return ResourceManager.GetString("Toggleconsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type values separated with space.
        /// </summary>
        public static string ToggleWindow_Hint {
            get {
                return ResourceManager.GetString("ToggleWindow_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Tool .
        /// </summary>
        public static string ToggleWindow_Title {
            get {
                return ResourceManager.GetString("ToggleWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unbindall.
        /// </summary>
        public static string Unbindall {
            get {
                return ResourceManager.GetString("Unbindall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} command execution.
        /// </summary>
        public static string UnknownCommandExecution_Format {
            get {
                return ResourceManager.GetString("UnknownCommandExecution_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        public static string Voicerecord {
            get {
                return ResourceManager.GetString("Voicerecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        public static string VolumeIncrease_ComboboxItem {
            get {
                return ResourceManager.GetString("VolumeIncrease_ComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce volume.
        /// </summary>
        public static string VolumeReduce_ComboboxItem {
            get {
                return ResourceManager.GetString("VolumeReduce_ComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume regulator.
        /// </summary>
        public static string VolumeRegulator {
            get {
                return ResourceManager.GetString("VolumeRegulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom sens. ratio.
        /// </summary>
        public static string zoom_sensitivity_ratio_mouse {
            get {
                return ResourceManager.GetString("zoom_sensitivity_ratio_mouse", resourceCulture);
            }
        }
    }
}
