//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionCategory_Button {
            get {
                return ResourceManager.GetString("ActionCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Button {
            get {
                return ResourceManager.GetString("Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom aliases.
        /// </summary>
        public static string Alias_Binding {
            get {
                return ResourceManager.GetString("Alias_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto buy.
        /// </summary>
        public static string AutoBuy {
            get {
                return ResourceManager.GetString("AutoBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        public static string Bomb {
            get {
                return ResourceManager.GetString("Bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy menu.
        /// </summary>
        public static string BuyMenu {
            get {
                return ResourceManager.GetString("BuyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy items.
        /// </summary>
        public static string BuyScenario {
            get {
                return ResourceManager.GetString("BuyScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy scenario.
        /// </summary>
        public static string BuyScenarioCategory_Button {
            get {
                return ResourceManager.GetString("BuyScenarioCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call vote.
        /// </summary>
        public static string CallVote {
            get {
                return ResourceManager.GetString("CallVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client commands.
        /// </summary>
        public static string CategoryClientCommands {
            get {
                return ResourceManager.GetString("CategoryClientCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common actions.
        /// </summary>
        public static string CategoryCommonActions {
            get {
                return ResourceManager.GetString("CategoryCommonActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string CategoryCommunication {
            get {
                return ResourceManager.GetString("CategoryCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosshair.
        /// </summary>
        public static string CategoryCrosshair {
            get {
                return ResourceManager.GetString("CategoryCrosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string CategoryEquipment {
            get {
                return ResourceManager.GetString("CategoryEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse settings.
        /// </summary>
        public static string CategoryMouseSettings {
            get {
                return ResourceManager.GetString("CategoryMouseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string CategoryMovement {
            get {
                return ResourceManager.GetString("CategoryMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net_graph settings.
        /// </summary>
        public static string CategoryNetGraphSettings {
            get {
                return ResourceManager.GetString("CategoryNetGraphSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CategoryOther {
            get {
                return ResourceManager.GetString("CategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmup.
        /// </summary>
        public static string CategoryWarmup {
            get {
                return ResourceManager.GetString("CategoryWarmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global chat.
        /// </summary>
        public static string ChatMessage {
            get {
                return ResourceManager.GetString("ChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose team.
        /// </summary>
        public static string ChooseTeam {
            get {
                return ResourceManager.GetString("ChooseTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear console.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear decals.
        /// </summary>
        public static string Cleardecals {
            get {
                return ResourceManager.GetString("Cleardecals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name:.
        /// </summary>
        public static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command radio.
        /// </summary>
        public static string CommandRadio {
            get {
                return ResourceManager.GetString("CommandRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands executed by default.
        /// </summary>
        public static string CommandsByDefault_Hint {
            get {
                return ResourceManager.GetString("CommandsByDefault_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands bound to custom alias.
        /// </summary>
        public static string CommandsInAlias_Hint {
            get {
                return ResourceManager.GetString("CommandsInAlias_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config name.
        /// </summary>
        public static string ConfigName_Hint {
            get {
                return ResourceManager.GetString("ConfigName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to csgo/cfg.
        /// </summary>
        public static string CsgoCfgPath_Hint {
            get {
                return ResourceManager.GetString("CsgoCfgPath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle crosshairs.
        /// </summary>
        public static string CycleCrosshair {
            get {
                return ResourceManager.GetString("CycleCrosshair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades.
        /// </summary>
        public static string CycleGrenades {
            get {
                return ResourceManager.GetString("CycleGrenades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        public static string DecoyGrenade {
            get {
                return ResourceManager.GetString("DecoyGrenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default commands.
        /// </summary>
        public static string Default_Binding {
            get {
                return ResourceManager.GetString("Default_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display damage OFF.
        /// </summary>
        public static string DisplayDamageOff {
            get {
                return ResourceManager.GetString("DisplayDamageOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display damage ON.
        /// </summary>
        public static string DisplayDamageOn {
            get {
                return ResourceManager.GetString("DisplayDamageOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string DropWeapon {
            get {
                return ResourceManager.GetString("DropWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duck.
        /// </summary>
        public static string Duck {
            get {
                return ResourceManager.GetString("Duck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute command.
        /// </summary>
        public static string ExecCustomCmds {
            get {
                return ResourceManager.GetString("ExecCustomCmds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra alias.
        /// </summary>
        public static string ExtraAlias {
            get {
                return ResourceManager.GetString("ExtraAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra alias set.
        /// </summary>
        public static string ExtraAliasSet {
            get {
                return ResourceManager.GetString("ExtraAliasSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string ExtraCategory_Button {
            get {
                return ResourceManager.GetString("ExtraCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashbang.
        /// </summary>
        public static string Flashbang {
            get {
                return ResourceManager.GetString("Flashbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From_Label {
            get {
                return ResourceManager.GetString("From_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string GameSettingsCategory_Button {
            get {
                return ResourceManager.GetString("GameSettingsCategory_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string Gear1 {
            get {
                return ResourceManager.GetString("Gear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West + helmet.
        /// </summary>
        public static string Gear2 {
            get {
                return ResourceManager.GetString("Gear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus.
        /// </summary>
        public static string Gear3 {
            get {
                return ResourceManager.GetString("Gear3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate .cfg.
        /// </summary>
        public static string GenerateConfig_Button {
            get {
                return ResourceManager.GetString("GenerateConfig_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate crosshairs.
        /// </summary>
        public static string GenerateCrosshairs_Button {
            get {
                return ResourceManager.GetString("GenerateCrosshairs_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God mode.
        /// </summary>
        public static string God {
            get {
                return ResourceManager.GetString("God", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graffiti menu.
        /// </summary>
        public static string GraffitiMenu {
            get {
                return ResourceManager.GetString("GraffitiMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molotov.
        /// </summary>
        public static string Grenade1 {
            get {
                return ResourceManager.GetString("Grenade1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        public static string Grenade2 {
            get {
                return ResourceManager.GetString("Grenade2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashbang.
        /// </summary>
        public static string Grenade3 {
            get {
                return ResourceManager.GetString("Grenade3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE.
        /// </summary>
        public static string Grenade4 {
            get {
                return ResourceManager.GetString("Grenade4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        public static string Grenade5 {
            get {
                return ResourceManager.GetString("Grenade5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades.
        /// </summary>
        public static string Grenades {
            get {
                return ResourceManager.GetString("Grenades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 1.
        /// </summary>
        public static string Health_Style0 {
            get {
                return ResourceManager.GetString("Health_Style0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 2.
        /// </summary>
        public static string Health_Style1 {
            get {
                return ResourceManager.GetString("Health_Style1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova.
        /// </summary>
        public static string Heavy1 {
            get {
                return ResourceManager.GetString("Heavy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XM1014.
        /// </summary>
        public static string Heavy2 {
            get {
                return ResourceManager.GetString("Heavy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sawed-Off/Mag7.
        /// </summary>
        public static string Heavy3 {
            get {
                return ResourceManager.GetString("Heavy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M249.
        /// </summary>
        public static string Heavy4 {
            get {
                return ResourceManager.GetString("Heavy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negev.
        /// </summary>
        public static string Heavy5 {
            get {
                return ResourceManager.GetString("Heavy5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE grenade.
        /// </summary>
        public static string HEGrenade {
            get {
                return ResourceManager.GetString("HEGrenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Impulse101 {
            get {
                return ResourceManager.GetString("Impulse101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect weapon.
        /// </summary>
        public static string InspectWeapon {
            get {
                return ResourceManager.GetString("InspectWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumpthrow script.
        /// </summary>
        public static string Jumpthrow {
            get {
                return ResourceManager.GetString("Jumpthrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard_Binding {
            get {
                return ResourceManager.GetString("Keyboard_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} pressure.
        /// </summary>
        public static string KeyDown1_Format {
            get {
                return ResourceManager.GetString("KeyDown1_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} pressure when {1} is pressed.
        /// </summary>
        public static string KeyDown2_Format {
            get {
                return ResourceManager.GetString("KeyDown2_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key pressure.
        /// </summary>
        public static string KeyPressure_Label {
            get {
                return ResourceManager.GetString("KeyPressure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key release.
        /// </summary>
        public static string KeyRelease_Label {
            get {
                return ResourceManager.GetString("KeyRelease_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} release.
        /// </summary>
        public static string KeyUp1_Format {
            get {
                return ResourceManager.GetString("KeyUp1_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} release when {1} is pressed.
        /// </summary>
        public static string KeyUp2_Format {
            get {
                return ResourceManager.GetString("KeyUp2_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knife.
        /// </summary>
        public static string Knife {
            get {
                return ResourceManager.GetString("Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last weapon.
        /// </summary>
        public static string LastWeaponUsed {
            get {
                return ResourceManager.GetString("LastWeaponUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightBlue.
        /// </summary>
        public static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom acceleration.
        /// </summary>
        public static string m_customaccel {
            get {
                return ResourceManager.GetString("m_customaccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom acceleration exponent.
        /// </summary>
        public static string m_customaccel_exponent {
            get {
                return ResourceManager.GetString("m_customaccel_exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw input.
        /// </summary>
        public static string m_rawinput {
            get {
                return ResourceManager.GetString("m_rawinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Maker [eng].
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        public static string Microphone {
            get {
                return ResourceManager.GetString("Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molotov.
        /// </summary>
        public static string Molotov {
            get {
                return ResourceManager.GetString("Molotov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        public static string Moveleft {
            get {
                return ResourceManager.GetString("Moveleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        public static string Moveright {
            get {
                return ResourceManager.GetString("Moveright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noclip.
        /// </summary>
        public static string Noclip {
            get {
                return ResourceManager.GetString("Noclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glock/USP.
        /// </summary>
        public static string Pistol1 {
            get {
                return ResourceManager.GetString("Pistol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual berettas.
        /// </summary>
        public static string Pistol2 {
            get {
                return ResourceManager.GetString("Pistol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P250.
        /// </summary>
        public static string Pistol3 {
            get {
                return ResourceManager.GetString("Pistol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZ75/Fiveseven/Tec9.
        /// </summary>
        public static string Pistol4 {
            get {
                return ResourceManager.GetString("Pistol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deagle.
        /// </summary>
        public static string Pistol5 {
            get {
                return ResourceManager.GetString("Pistol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistols.
        /// </summary>
        public static string Pistols {
            get {
                return ResourceManager.GetString("Pistols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift for key sequence creating.
        /// </summary>
        public static string PressShift_Hint {
            get {
                return ResourceManager.GetString("PressShift_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary weapon.
        /// </summary>
        public static string PrimaryWeapon {
            get {
                return ResourceManager.GetString("PrimaryWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuy.
        /// </summary>
        public static string Rebuy {
            get {
                return ResourceManager.GetString("Rebuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove_Button {
            get {
                return ResourceManager.GetString("Remove_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report radio.
        /// </summary>
        public static string ReportRadio {
            get {
                return ResourceManager.GetString("ReportRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galil/Famas.
        /// </summary>
        public static string Rifle1 {
            get {
                return ResourceManager.GetString("Rifle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AK47/M4.
        /// </summary>
        public static string Rifle2 {
            get {
                return ResourceManager.GetString("Rifle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSG08.
        /// </summary>
        public static string Rifle3 {
            get {
                return ResourceManager.GetString("Rifle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG553/AUG.
        /// </summary>
        public static string Rifle4 {
            get {
                return ResourceManager.GetString("Rifle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWP.
        /// </summary>
        public static string Rifle5 {
            get {
                return ResourceManager.GetString("Rifle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G3SG1/SCAR.
        /// </summary>
        public static string Rifle6 {
            get {
                return ResourceManager.GetString("Rifle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifles.
        /// </summary>
        public static string Rifles {
            get {
                return ResourceManager.GetString("Rifles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save config.
        /// </summary>
        public static string SaveConfig_Button {
            get {
                return ResourceManager.GetString("SaveConfig_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string Scoreboard {
            get {
                return ResourceManager.GetString("Scoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Hint {
            get {
                return ResourceManager.GetString("Search_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary fire.
        /// </summary>
        public static string SecondaryFire {
            get {
                return ResourceManager.GetString("SecondaryFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary weapon.
        /// </summary>
        public static string SecondaryWeapon {
            get {
                return ResourceManager.GetString("SecondaryWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select config.
        /// </summary>
        public static string SelectConfig_Button {
            get {
                return ResourceManager.GetString("SelectConfig_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next weapon.
        /// </summary>
        public static string SelectNextWeapon {
            get {
                return ResourceManager.GetString("SelectNextWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous weapon.
        /// </summary>
        public static string SelectPreviousWeapon {
            get {
                return ResourceManager.GetString("SelectPreviousWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity.
        /// </summary>
        public static string sensitivity {
            get {
                return ResourceManager.GetString("sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show avatars.
        /// </summary>
        public static string ShowAvatars {
            get {
                return ResourceManager.GetString("ShowAvatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show alive count.
        /// </summary>
        public static string ShowCount {
            get {
                return ResourceManager.GetString("ShowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show team equipment.
        /// </summary>
        public static string ShowTeamEquipment {
            get {
                return ResourceManager.GetString("ShowTeamEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac10/MP9.
        /// </summary>
        public static string Smg1 {
            get {
                return ResourceManager.GetString("Smg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP7.
        /// </summary>
        public static string Smg2 {
            get {
                return ResourceManager.GetString("Smg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMP45.
        /// </summary>
        public static string Smg3 {
            get {
                return ResourceManager.GetString("Smg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P90.
        /// </summary>
        public static string Smg4 {
            get {
                return ResourceManager.GetString("Smg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP-Bizon.
        /// </summary>
        public static string Smg5 {
            get {
                return ResourceManager.GetString("Smg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        public static string SMGs {
            get {
                return ResourceManager.GetString("SMGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke grenade.
        /// </summary>
        public static string Smokegrenade {
            get {
                return ResourceManager.GetString("Smokegrenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standart radio.
        /// </summary>
        public static string StandartRadio {
            get {
                return ResourceManager.GetString("StandartRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step_Label {
            get {
                return ResourceManager.GetString("Step_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team chat.
        /// </summary>
        public static string TeamMessage {
            get {
                return ResourceManager.GetString("TeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To_Label {
            get {
                return ResourceManager.GetString("To_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string ToggleConsole {
            get {
                return ResourceManager.GetString("ToggleConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle inventory display.
        /// </summary>
        public static string ToggleInventoryDisplay {
            get {
                return ResourceManager.GetString("ToggleInventoryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type values separated with space.
        /// </summary>
        public static string ToggleWindow_Hint {
            get {
                return ResourceManager.GetString("ToggleWindow_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Tool .
        /// </summary>
        public static string ToggleWindow_Title {
            get {
                return ResourceManager.GetString("ToggleWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        public static string VolumeIncrease_ComboboxItem {
            get {
                return ResourceManager.GetString("VolumeIncrease_ComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce volume.
        /// </summary>
        public static string VolumeReduce_ComboboxItem {
            get {
                return ResourceManager.GetString("VolumeReduce_ComboboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume regulator.
        /// </summary>
        public static string VolumeRegulator {
            get {
                return ResourceManager.GetString("VolumeRegulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus.
        /// </summary>
        public static string Zeus {
            get {
                return ResourceManager.GetString("Zeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom sens. ratio.
        /// </summary>
        public static string zoom_sensitivity_ratio_mouse {
            get {
                return ResourceManager.GetString("zoom_sensitivity_ratio_mouse", resourceCulture);
            }
        }
    }
}
